### ISSUE TITLE
Get-LogicMonitorAlerts

### ISSUE THREAD

**Issue by pmilano1** [wetling23/logicmonitor-posh-module#3]
I notice it's not broadcast in the module - figured I would ask what its status is before I begin hacking and putting in a PR. Any input?

**Comment by wetling23** [comment]
Sorry, I just saw this. I wish I got notifications. 

Anyway, It isn't in the module because of a limitation in the API. Currently, we can only retrieve 10000 alerts, so I didn't want to provide a cmdlet that indicates you can get all alerts, if that isn't the case. 

That said, if you'd like to submit a pr, please feel free.

**Comment by wetling23** [comment]
added the requested command
